# Use this file to store passwords to services that your server you use. When
# the server starts, the passwords will be automatically loaded and can be
# accessed from the `session.passwords` field. If you don't have access to a
# session object, passwords can also be accessed from
# `Serverpod.instance.passwords`. You can provide different passwords for
# different run configurations. If you want the same password for any
# configuration used, place it under `shared`.
#
# Note that this file should not be under version control. Store it in a safe
# place.

# Save passwords used across all configurations here.
shared:
  mySharedPassword: 'my password'

# These are passwords used when running the server locally in development mode
development:
  geminiApiKey: "--- Your Gemini Api Key ---"
  database: 'KJKwXMQLoQiSKbF-8M7A4sDi0iWa_pDX'
  redis: 'GowjTovQ6cyRguLrGLxFgaEcbsvaEHZZ'

  # The service secret is used to communicate between servers and to access the
  # service protocol.
  serviceSecret: 'MAJ9TtBT-gTThvtgwWnJYFJjunHskxKb'

  emailSecretHashPepper: 'I1k9ooe0WqqLeugW5-z4HD4r4Jf9L838'
  jwtHmacSha512PrivateKey: 'MAEmRb_RL8uq8Ic-sWDFfFfOLDRsr1YI'
  jwtRefreshTokenHashPepper: 'KoU5q1Z-U110CZJXKHrEMrpOmmxBpR-M'
  # serverSideSessionKeyHashPepper: 'IlfAr7f4MxhkaNTFmujgzDYLD02VZ47O'

test:
  geminiApiKey: "--- Your Test Gemini Api Key ---"
  database: 'DaBA2ec_HKHwJnXQhg9zBSVTOKmaPptV'
  redis: 'Fc2mjQpnvJ60bcN07tSiWhRAQKMy9ZCj'

  emailSecretHashPepper: 'KxdIGFErs1TS9rDVnSyKe4m0AsUPZmOP'
  jwtHmacSha512PrivateKey: 'jGlYK7WmOv8CUz_FOx7matK5SmXkAMHf'
  jwtRefreshTokenHashPepper: '0fah6NIXEXnQ9iDlszGHKAILO3G56Fq_'
  # serverSideSessionKeyHashPepper: 'rnfDORXsgByFlt6ICvrATc8X6pYuJgp0'

# Passwords used in your staging environment if you use one. The default setup
# use a password for Redis.
staging:
  geminiApiKey: "--- Your Staging Gemini Api Key ---"
  database: 'x0q-_1xTu6JAsSUv_P-6GsbcjxPRPE0Z'
  serviceSecret: '4HEbQdyIYRcS-rA4D5qGtorz3ucWEbIa'

  emailSecretHashPepper: 'R6OleonX47OZRgUzOCw5rf2Ov1JhsMYG'
  jwtHmacSha512PrivateKey: 'o5HCiCoGjcvIHAUDVFPa0QbQ1oivujJE'
  jwtRefreshTokenHashPepper: 'IrDcNEatRUza0w9TFrR_qhysBoiMzUM5'
  # serverSideSessionKeyHashPepper: 'v2kgn1ppUphw99yAQiFywH2OaHyU4bSo'

# Passwords used in production mode.
production:
  geminiApiKey: "--- Your Production Gemini Api Key ---"
  database: '-ZaNY-DXjjiGVA_MJ9Tz2elGItdVfIlp'
  serviceSecret: 'PlnYgf2aSWaVqwMSwI9WQK_qzcnDKCzv'

  emailSecretHashPepper: 'DOVoqz1PcJTiPtiObkP4fJftJo34r1ew'
  jwtHmacSha512PrivateKey: 'r-9hCETnETrZsNA9mZPrbQq6sTfF-OWG'
  jwtRefreshTokenHashPepper: '2tZeTcPb_3C3M7l2yLMJqsIa-sgsLe13'
  # serverSideSessionKeyHashPepper: 'OmzgdknCYW83MVoxyPBgzYBMJSLjHLcW'
