# Use this file to store passwords to services that your server you use. When
# the server starts, the passwords will be automatically loaded and can be
# accessed from the `session.passwords` field. If you don't have access to a
# session object, passwords can also be accessed from
# `Serverpod.instance.passwords`. You can provide different passwords for
# different run configurations. If you want the same password for any
# configuration used, place it under `shared`.
#
# Note that this file should not be under version control. Store it in a safe
# place.

# These are passwords used when running the server locally in development mode
development:
  geminiApiKey: "--- Your Gemini Api Key ---"
  database: 'BIOU7egAi5HEwP1QMXpK22If7pR7Bbxm'
  redis: 'sMm2_qRg9zlBMW8ClDva-JDhrMNVWiEi'

  # The service secret is used to communicate between servers and to access the
  # service protocol.
  serviceSecret: 'awxwqrmlGk5VBADLiF24P0_bOu4RFF5Q'

test:
  geminiApiKey: "--- Your Test Gemini Api Key ---"
  database: 'OYsc1TmYTfy_tSvVV70-lO-2RnC0KhMJ'
  redis: 'JwgLHBNCRDSmkBImNK3ZZ2-k9gl5xSU6'

# Passwords used in your staging environment if you use one. The default setup
# use a password for Redis.
staging:
  geminiApiKey: "--- Your Staging Gemini Api Key ---"
  database: 'C9SIOQlrS9HAVg-tJoldKUL_vEltaEEN'
  serviceSecret: '3M3aFm3zbKDjoTgoJBwKpuvaUdbVlpg8'

# Passwords used in production mode.
production:
  geminiApiKey: "--- Your Production Gemini Api Key ---"
  database: '_2beuZXAG5KkmNCkjZJMmrW7YvjkjigM'
  serviceSecret: 'e72FscLJ_Kje7rrTKNOPeiMEAitrugC9'
