# Use this file to store passwords to services that your server you use. When
# the server starts, the passwords will be automatically loaded and can be
# accessed from the `session.passwords` field. If you don't have access to a
# session object, passwords can also be accessed from
# `Serverpod.instance.passwords`. You can provide different passwords for
# different run configurations. If you want the same password for any
# configuration used, place it under `shared`.
#
# Note that this file should not be under version control. Store it in a safe
# place.

# Save passwords used across all configurations here.
shared:
  gemini: "-- your gemini key --"

# These are passwords used when running the server locally in development mode
development:
  database: 'wClaEi4Z6nMRJ175tOb_ZApxlcfbgwvt'
  redis: 'SdPBuoPS-VHGp5cbID3KnbKoEb2Wgqyt'

  # The service secret is used to communicate between servers and to access the
  # service protocol.
  serviceSecret: 'x5GMpnTuQYNttKLMgIb11qvEf7g-dwVR'
  
  # Authentication managers configuration
  authSessionsSessionKeyHashPepper: 'test_session_key_pepper'

  # Email Sign In configuration
  emailSecretHashPepper: 'test_email_password_hash_pepper'

test:
  database: 'dBXVB1fu0UEsdUZujH7PISOxJwULy2cM'
  redis: 'HzM3eq8u-rimygaEYJ45Lnhx8YO1DwZG'

# Passwords used in your staging environment if you use one. The default setup
# use a password for Redis.
staging:
  database: 'xnYGIvjS6n8KyXCcwMmIL4_yiV5rSiGS'
  serviceSecret: 'KhJ8nkuDorbLeWjSiBoSZeLJ-mLlkiwI'

# Passwords used in production mode.
production:
  database: '_rIUlTclHMq0fvGUugq0vBQ5ytyVBWeO'
  serviceSecret: 'Tqc3b3vy6IvFxIKDbj0pMNTF7_LVUa7F'
